#!/bin/bash
# System upgrade script
COMPOSER_GLOBAL_DIR="$HOME/.composer"

echo '===> Self update '
cd /usr/local/opt/system_update && git pull

printf '\e[32m===> done \e[39m\n\n'


printf '\e[32m===> done \e[39m\n\n'
echo '===> Update macOS'

softwareupdate -i -a 

printf '\e[32m===> done \e[39m\n\n'

echo '===> Update homebrew '

/usr/local/bin/brew doctor;
/usr/local/bin/brew update;

printf '\e[32m===> done \e[39m\n\n'
echo '===> Upgrade homebrew'

/usr/local/bin/brew upgrade;

printf '\e[32m===> done \e[39m\n\n'
echo '===> Upgrade homebrew cask'

/usr/local/bin/brew cask upgrade;

printf '\e[32m===> done \e[39m\n\n'
echo '===> Cleanup homebrew'

/usr/local/bin/brew cleanup -s;

printf '\e[32m===> done \e[39m\n\n'
echo '===> Update NPM'

for package in $(npm -g outdated --parseable --depth=0 | cut -d: -f2 | sed 's/@.*//g')
do
    npm -g install "$package@latest"
done

printf '\e[32m===> done \e[39m\n\n'
echo '===> Update macOS app store'
mas upgrade;

printf '\e[32m===> done \e[39m\n\n'
echo '===> Update Ruby'

sudo gem update --system
sudo gem update `gem list | cut -d " " -f 1` -n /usr/local/bin;

printf '\e[32m===> done \e[39m\n\n'

if [ -d "$COMPOSER_GLOBAL_DIR" ]; then
    echo '===> Update Composer'
    composer global update;

    printf '\e[32m===> done \e[39m\n\n'
fi
